[package]
name = "strobmock"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/strobeops/strobmock"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
bytes = "1.12.1"
axum = "0.8.9"
clap = { version = "4.6.6", features = ["derive"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tokio-stream = "0.1.17"
tracing-appender = "0.2.5"
tower-http = { version = "0.7.1", features = ["trace"] }

[dev-dependencies]
tower = { version = "0.5.3", features = ["util"] }
http-body-util = "0.1.5"
http = "1.5.0"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
strip = true

[workspace.metadata.release]
# Custom prefix for your Git tags (default is empty or the version number)
tag-prefix = ""
# Automatically push to your remote repository after committing and tagging
push = false
# Skip publishing to crates.io (useful for private binaries/libraries)
publish = false
# Explicitly forces all workspace members to bump version together
shared-version = true
