---
name: CI

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - '**.md'
      - 'LICENSE*'
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - 'docs/**'
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - 'LICENSE*'
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - 'docs/**'

# Auto-cancel superseded workflow runs on the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: riccione/github-workflows/.github/workflows/rust-ci.yml@309464f75695501b26e988010273cc182de38f3a
